M48
; DRILL file {KiCad (6.0.7-1)-1} date 2024 July 24, Wednesday 16:53:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-24T16:53:13+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X393.55Y-93.95
X397.15Y-93.95
X402.9Y-93.95
X406.5Y-93.95
T0
M30
